# .github/workflows/test.yml

name: Test

on:
  pull_request:

  jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - name: Use Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '18'

        - run: yarn install

        - run: yarn build

    build:
      needs: test
      runs-on: ubuntu-latest
      steps:

        - name: Check Out Code
          uses: actions/checkout@v2
          
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
        
        - name: Build Docker Image
          uses: docker/build-push-action@v2
          with:
            context: .
            push: false
